### ISSUE TITLE
Handle Ambiguity in Matchday Retrieval

### ISSUE THREAD

**Issue by MauroAndretta** [MauroAndretta/AIFootballPredictions#3]
Currently, the `acquire_next_matches.py` script fetches the next matchday data based on the current matchday provided by the API. However, the behavior of the script is ambiguous depending on the day and time it is executed:

- **Case 1**: When the script is executed during a matchday where some matches have already been played and others are yet to be played, the script considers the "next matches" to be the remaining matches of the current matchday. This is not always the desired behavior.
- **Case 2**: When the script is executed before any matches of the current matchday have started, it correctly identifies the next matches as those in the current matchday.

This inconsistency can lead to confusion and incorrect predictions.

## Expected Behavior

The script should consistently fetch the upcoming matches, regardless of whether some matches in the current matchday have already been played. The user should be able to configure whether they want to:

## Proposed Solution

1. **Add a Configuration Option**: Introduce a flag or parameter (e.g., `--include-ongoing-matches`) that allows the user to specify whether they want to include ongoing matches from the current matchday or skip to the next matchday.

2. **Implement Logic Based on the Configuration**:
    - If `--include-ongoing-matches` is set to `True`, include the remaining matches of the current matchday.
    - If `--include-ongoing-matches` is set to `False`, check if any matches have already been played in the current matchday. If they have, skip to the next matchday.

3. **Improve Matchday Management**: Implement a robust method to handle matchdays, ensuring that the script correctly identifies the upcoming matches based on the user's preference.

## Steps to Reproduce

1. Execute the `acquire_next_matches.py` script during a matchday when some matches have already been played.
2. Observe that the script fetches the remaining matches of the current matchday as the "next matches".
3. Execute the script before any matches of a matchday have started.
4. Observe that the script correctly identifies all matches of the current matchday as the "next matches".

**Comment by MauroAndretta** [comment]
Added logic to predict only matches that need to be played. Using a check with the current date in which the script is executed and the date time of the match.

**Comment by SoccerCashUK** [comment]
python scripts/acquire_next_matches.py --get_teams_names_dir data/processed --next_matches_output_file data/next_matches.json
Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\AIFootballPredictions-main\AIFootballPredictions-main\scripts\acquire_next_matches.py", line 351, in <module>
    get_next_matches(HEADERS, BASE_URL)
  File "C:\Users\Iphon\Downloads\AIFootballPredictions-main\AIFootballPredictions-main\scripts\acquire_next_matches.py", line 198, in get_next_matches
    raise ValueError(f"Environment variable {var} is not set. Please see the README for more information.")
ValueError: Environment variable API_FOOTBALL_DATA is not set. Please see the README for more information.
